Algoritmo "FACCAT - Ex. 57"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresenta os números de 1 a 10.
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 04/09/2025
Var
   contador: inteiro

Inicio
   contador := 1
   repita
      escreval("N: " + numpcarac(contador))
      contador := contador + 1
   ate (contador > 10)

Fimalgoritmo