Algoritmo "FACCAT - Ex. 51"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresenta os números de 10 a 1.
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 04/09/2025
Var
   contador: inteiro

Inicio
   contador := 10
   enquanto (contador >= 1) faca
      escreval("N: " + numpcarac(contador))
      contador := contador - 1
   fimenquanto

Fimalgoritmo