Algoritmo "FACCAT - Ex. 67"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula a apresenta a média aritmetica dos inteiros entre 15 e
//               100.
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 04/09/2025
Var
   contador: inteiro
   media: real

Inicio
   para contador de 15 ate 100 faca
    media := media + contador / 86
   fimpara
   escreval("A média é: "+numpcarac(media))

Fimalgoritmo