algoritmo "manzano-ex5.6.1-1f"
// Disciplina  : Lógica de Programação
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresenta os números divisíveis por 4 menores que 200.
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 24/09/2025
var
   contador: inteiro

inicio
   para contador de 1 ate 199 faca
      se (contador % 4 = 0) entao
         escreval(contador)
      fimse
   fimpara

fimalgoritmo