algoritmo "manzano-ex5.6.1-1a"
// Disciplina  : Lógica de Programação
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresenta os quadrados dos valores de 15 até 200.
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 24/09/2025
var
   quadrado: inteiro
   contador: inteiro

inicio
   para contador de 15 ate 200 faca
      quadrado := contador * contador
      escreval(numpcarac(contador)+"² = "+numpcarac(quadrado))
   fimpara

fimalgoritmo