algoritmo "manzano-ex4.7-4k"
// Disciplina  : Lógica de Programação
// Professor   : Jailson Costa dos Santos
// Descrição   : Lê um número inteiro e o apresenta caso não seja maior que 3.
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 18/09/2025
var
   numero: inteiro

inicio
   escreval("Insira um número: (inteiro)")
   escreva("R: ")
   leia(numero)

   se (numero <= 3) entao
      escreval(numero)
   fimse

fimalgoritmo