algoritmo "manzano-ex5.6.1-1c"
// Disciplina  : Lógica de Programação
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresenta a soma dos primeiros 100 números
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 24/09/2025
var
   somatorio: inteiro
   contador: inteiro

inicio
   para contador de 1 ate 100 faca
      somatorio := somatorio + contador
      escreval(somatorio)
   fimpara

fimalgoritmo