algoritmo "manzano-ex5.2.1-1a"
// Disciplina  : Lógica de Programação
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 24/09/2025
var
   contador: inteiro

inicio
   contador := 15
   repita
      escreval(contador)
      contador := contador + 1
   ate (contador > 200)

fimalgoritmo