algoritmo "manzano-ex5.6.1-1d"
// Disciplina  : Lógica de Programação
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresenta a soma dos pares de 1 até 500.
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 24/09/2025
var
   somatorio: inteiro
   contador: inteiro

inicio
   para contador de 1 ate 500 faca
      se (contador % 2 = 0) entao
         somatorio := somatorio + contador
      escreval(somatorio)
      fimse
   fimpara

fimalgoritmo