algoritmo "manzano-ex5.6.1-1e"
// Disciplina  : Lógica de Programação
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresenta os inteiros ímpares entre 0 e 20.
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 24/09/2025
var
   contador: inteiro

inicio
   para contador de 0 ate 20 faca
      se (contador % 2 = 1) entao
         escreval(contador)
      fimse
   fimpara

fimalgoritmo