Algoritmo "gpt_09_15_ex8"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresenta a soma dos quadrados dos números pares entre 1 e 50.
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 15/09/2025
Var
   contador: inteiro
   soma: inteiro

Inicio
      para contador de 1 ate 50 faca
      se (contador mod 2 = 0) entao
       soma := soma + contador * contador
      fimse
      fimpara
      escreval("A soma dos quadrados pares é: "+numpcarac(soma))

Fimalgoritmo