Algoritmo "gpt_09_15_ex2"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresenta a tabuada de 0 a 10 de um número apresentado pelo
//               usuário.
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 15/09/2025
Var
   numero: inteiro
   contador: inteiro

Inicio
   escreval("Insira um número: (inteiro)")
   leia(numero)

   escreval()
   para contador de 1 ate 10 faca
      escreval(numpcarac(numero)+" x "+numpcarac(contador)+" = "+numpcarac(numero * contador))
   fimpara


Fimalgoritmo