Algoritmo "gpt_09_19_ex5"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Requisita um número positivo ao usuário.
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 19/09/2025
Var
   numero: inteiro

Inicio
   repita
      escreval("Insira um número: (inteiro)")
      escreva("R: ")
      leia(numero)
      limpatela()
      escreval("O NÚMERO DEVE SER POSITIVO")
   ate (numero > 0)
   limpatela()
   escreval("AGORA SIM, UM NÚMERO POSITIVO")


Fimalgoritmo