algoritmo "laco_de_repeticao"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exemplo de laço de repetição
// Autor(a)    : Matheus de Oliveira Caldas
// Data atual  : 12/09/2025
var
   // Seção de Declarações das variáveis
   numero: inteiro

inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   enquanto (numero < 10) faca
      escreval("Matheus")
      numero := numero + 1
   fimenquanto

fimalgoritmo